import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MessageCircleMore } from "lucide-react";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} antialiased max-w-screen-xl mx-auto px-4
        `}
      >
        <Navbar />
        {children}
        <Link href={"/chat"} id='chatbot' className="p-6 rounded-full bg-green-700 hover:bg-green-600 fixed bottom-10 right-10 cursor-pointer">
          <MessageCircleMore className="text-white font-extrabold" size={28} />
        </Link>
        <Footer />
      </body>
    </html>
  );
}
